package com.practicalchristian.app.core.localdatasource.helpers

enum class BibleBook(val value: String, val chapters: Int) {
    GENESIS(value = "genesis", chapters = 50),
    EXODUS(value = "exodus", chapters = 40),
    LEVITICUS(value = "leviticus", chapters = 27),
    NUMBERS(value = "numbers", chapters = 36),
    DEUTERONOMY(value = "deuteronomy", chapters = 34),
    JOSHUA(value = "joshua", chapters = 24),
    JUDGES(value = "judges", chapters = 21),
    RUTH(value = "ruth", chapters = 4),
    SAMUEL_1(value = "1 samuel", chapters = 31),
    SAMUEL_2(value = "2 samuel", chapters = 24),
    KINGS_1(value = "1 kings", chapters = 22),
    KINGS_2(value = "2 kings", chapters = 25),
    CHRONICLES_1(value = "1 chronicles", chapters = 29),
    CHRONICLES_2(value = "2 chronicles", chapters = 36),
    EZRA(value = "ezra", chapters = 10),
    NEHEMIAH(value = "nehemiah", chapters = 13),
    ESTHER(value = "esther", chapters = 10),
    JOB(value = "job", chapters = 42),
    PSALMS(value = "psalms", chapters = 150),
    PROVERBS(value = "proverbs", chapters = 31),
    ECCLESIASTES(value = "ecclesiastes", chapters = 12),
    SONG_OF_SOLOMON(value = "song of solomon", chapters = 8),
    ISAIAH(value = "isaiah", chapters = 66),
    JEREMIAH(value = "jeremiah", chapters = 52),
    LAMENTATIONS(value = "lamentations", chapters = 5),
    EZEKIEL(value = "ezekiel", chapters = 48),
    DANIEL(value = "daniel", chapters = 12),
    HOSEA(value = "hosea", chapters = 14),
    JOEL(value = "joel", chapters = 3),
    AMOS(value = "amos", chapters = 9),
    OBADIAH(value = "obadiah", chapters = 1),
    JONAH(value = "jonah", chapters = 4),
    MICAH(value = "micah", chapters = 7),
    NAHUM(value = "nahum", chapters = 3),
    HABAKKUK(value = "habakkuk", chapters = 3),
    ZEPHANIAH(value = "zephaniah", chapters = 3),
    HAGGAI(value = "haggai", chapters = 2),
    ZECHARIAH(value = "zechariah", chapters = 14),
    MALACHI(value = "malachi", chapters = 4),

    MATTHEW(value = "matthew", chapters = 28),
    MARK(value = "mark", chapters = 16),
    LUKE(value = "luke", chapters = 24),
    JOHN(value = "john", chapters = 21),
    ACTS(value = "acts", chapters = 28),
    ROMANS(value = "romans", chapters = 16),
    CORINTHIANS_1(value = "1 corinthians", chapters = 16),
    CORINTHIANS_2(value = "2 corinthians", chapters = 13),
    GALATIANS(value = "galatians", chapters = 6),
    EPHESIANS(value = "ephesians", chapters = 6),
    PHILIPPIANS(value = "philippians", chapters = 4),
    COLOSSIANS(value = "colossians", chapters = 4),
    THESSALONIANS_1(value = "1 thessalonians", chapters = 5),
    THESSALONIANS_2(value = "2 thessalonians", chapters = 3),
    TIMOTHY_1(value = "1 timothy", chapters = 6),
    TIMOTHY_2(value = "2 timothy", chapters = 4),
    TITUS(value = "titus", chapters = 3),
    PHILEMON(value = "philemon", chapters = 1),
    HEBREWS(value = "hebrews", chapters = 13),
    JAMES(value = "james", chapters = 5),
    PETER_1(value = "1 peter", chapters = 5),
    PETER_2(value = "2 peter", chapters = 3),
    JOHN_1(value = "1 john", chapters = 5),
    JOHN_2(value = "2 john", chapters = 1),
    JOHN_3(value = "3 john", chapters = 1),
    JUDE(value = "jude", chapters = 1),
    REVELATION(value = "revelation", chapters = 22),
}
