package com.practicalchristian.app.core.localdatasource.helpers

data class SequenceItem(val book: Int, val chapter: Int)

data class Sequence(val start: SequenceItem, val end: SequenceItem)

// TODO: The sequence will be replaced in a BIble JSON update. this place holder will be removed
val sequential = mutableListOf(
    // GENESIS
    Sequence(start = SequenceItem(book = 1, chapter = 1), end = SequenceItem(book = 1, chapter = 3)),
    Sequence(start = SequenceItem(book = 1, chapter = 4), end = SequenceItem(book = 1, chapter = 7)),
    Sequence(start = SequenceItem(book = 1, chapter = 8), end = SequenceItem(book = 1, chapter = 11)),
    Sequence(start = SequenceItem(book = 1, chapter = 12), end = SequenceItem(book = 1, chapter = 15)),
    Sequence(start = SequenceItem(book = 1, chapter = 16), end = SequenceItem(book = 1, chapter = 18)),
    Sequence(start = SequenceItem(book = 1, chapter = 19), end = SequenceItem(book = 1, chapter = 22)),
    Sequence(start = SequenceItem(book = 1, chapter = 23), end = SequenceItem(book = 1, chapter = 24)),
    Sequence(start = SequenceItem(book = 1, chapter = 25), end = SequenceItem(book = 1, chapter = 27)),
    Sequence(start = SequenceItem(book = 1, chapter = 28), end = SequenceItem(book = 1, chapter = 30)),
    Sequence(start = SequenceItem(book = 1, chapter = 31), end = SequenceItem(book = 1, chapter = 32)),
    Sequence(start = SequenceItem(book = 1, chapter = 33), end = SequenceItem(book = 1, chapter = 34)),
    Sequence(start = SequenceItem(book = 1, chapter = 35), end = SequenceItem(book = 1, chapter = 37)),
    Sequence(start = SequenceItem(book = 1, chapter = 38), end = SequenceItem(book = 1, chapter = 40)),
    Sequence(start = SequenceItem(book = 1, chapter = 41), end = SequenceItem(book = 1, chapter = 42)),
    Sequence(start = SequenceItem(book = 1, chapter = 43), end = SequenceItem(book = 1, chapter = 45)),
    Sequence(start = SequenceItem(book = 1, chapter = 46), end = SequenceItem(book = 1, chapter = 48)),
    Sequence(start = SequenceItem(book = 1, chapter = 49), end = SequenceItem(book = 1, chapter = 50)),
    // EXODUS
    Sequence(start = SequenceItem(book = 2, chapter = 1), end = SequenceItem(book = 2, chapter = 4)),
    Sequence(start = SequenceItem(book = 2, chapter = 5), end = SequenceItem(book = 2, chapter = 7)),
    Sequence(start = SequenceItem(book = 2, chapter = 8), end = SequenceItem(book = 2, chapter = 10)),
    Sequence(start = SequenceItem(book = 2, chapter = 11), end = SequenceItem(book = 2, chapter = 13)),
    Sequence(start = SequenceItem(book = 2, chapter = 14), end = SequenceItem(book = 2, chapter = 15)),
    Sequence(start = SequenceItem(book = 2, chapter = 16), end = SequenceItem(book = 2, chapter = 18)),
    Sequence(start = SequenceItem(book = 2, chapter = 19), end = SequenceItem(book = 2, chapter = 21)),
    Sequence(start = SequenceItem(book = 2, chapter = 22), end = SequenceItem(book = 2, chapter = 25)),
    Sequence(start = SequenceItem(book = 2, chapter = 26), end = SequenceItem(book = 2, chapter = 28)),
    Sequence(start = SequenceItem(book = 2, chapter = 29), end = SequenceItem(book = 2, chapter = 30)),
    Sequence(start = SequenceItem(book = 2, chapter = 31), end = SequenceItem(book = 2, chapter = 33)),
    Sequence(start = SequenceItem(book = 2, chapter = 34), end = SequenceItem(book = 2, chapter = 35)),
    Sequence(start = SequenceItem(book = 2, chapter = 36), end = SequenceItem(book = 2, chapter = 38)),
    Sequence(start = SequenceItem(book = 2, chapter = 39), end = SequenceItem(book = 2, chapter = 40)),
    // LEVITICUS
    Sequence(start = SequenceItem(book = 3, chapter = 1), end = SequenceItem(book = 3, chapter = 4)),
    Sequence(start = SequenceItem(book = 3, chapter = 5), end = SequenceItem(book = 3, chapter = 7)),
    Sequence(start = SequenceItem(book = 3, chapter = 8), end = SequenceItem(book = 3, chapter = 10)),
    Sequence(start = SequenceItem(book = 3, chapter = 11), end = SequenceItem(book = 3, chapter = 13)),
    Sequence(start = SequenceItem(book = 3, chapter = 14), end = SequenceItem(book = 3, chapter = 15)),
    Sequence(start = SequenceItem(book = 3, chapter = 16), end = SequenceItem(book = 3, chapter = 18)),
    Sequence(start = SequenceItem(book = 3, chapter = 19), end = SequenceItem(book = 3, chapter = 21)),
    Sequence(start = SequenceItem(book = 3, chapter = 22), end = SequenceItem(book = 3, chapter = 23)),
    Sequence(start = SequenceItem(book = 3, chapter = 24), end = SequenceItem(book = 3, chapter = 25)),
    Sequence(start = SequenceItem(book = 3, chapter = 26), end = SequenceItem(book = 3, chapter = 27)),
    // NUMBERS
    Sequence(start = SequenceItem(book = 4, chapter = 1), end = SequenceItem(book = 4, chapter = 3)),
    Sequence(start = SequenceItem(book = 4, chapter = 4), end = SequenceItem(book = 4, chapter = 6)),
    Sequence(start = SequenceItem(book = 4, chapter = 7), end = SequenceItem(book = 4, chapter = 9)),
    Sequence(start = SequenceItem(book = 4, chapter = 10), end = SequenceItem(book = 4, chapter = 12)),
    Sequence(start = SequenceItem(book = 4, chapter = 13), end = SequenceItem(book = 4, chapter = 15)),
    Sequence(start = SequenceItem(book = 4, chapter = 16), end = SequenceItem(book = 4, chapter = 18)),
    Sequence(start = SequenceItem(book = 4, chapter = 19), end = SequenceItem(book = 4, chapter = 21)),
    Sequence(start = SequenceItem(book = 4, chapter = 22), end = SequenceItem(book = 4, chapter = 24)),
    Sequence(start = SequenceItem(book = 4, chapter = 25), end = SequenceItem(book = 4, chapter = 27)),
    Sequence(start = SequenceItem(book = 4, chapter = 28), end = SequenceItem(book = 4, chapter = 30)),
    Sequence(start = SequenceItem(book = 4, chapter = 31), end = SequenceItem(book = 4, chapter = 32)),
    Sequence(start = SequenceItem(book = 4, chapter = 33), end = SequenceItem(book = 4, chapter = 36)),
    // DEUTERONOMY
    Sequence(start = SequenceItem(book = 5, chapter = 1), end = SequenceItem(book = 5, chapter = 2)),
    Sequence(start = SequenceItem(book = 5, chapter = 3), end = SequenceItem(book = 5, chapter = 4)),
    Sequence(start = SequenceItem(book = 5, chapter = 5), end = SequenceItem(book = 5, chapter = 7)),
    Sequence(start = SequenceItem(book = 5, chapter = 8), end = SequenceItem(book = 5, chapter = 10)),
    Sequence(start = SequenceItem(book = 5, chapter = 11), end = SequenceItem(book = 5, chapter = 13)),
    Sequence(start = SequenceItem(book = 5, chapter = 11), end = SequenceItem(book = 5, chapter = 13)),
    Sequence(start = SequenceItem(book = 5, chapter = 14), end = SequenceItem(book = 5, chapter = 16)),
    Sequence(start = SequenceItem(book = 5, chapter = 17), end = SequenceItem(book = 5, chapter = 19)),
    Sequence(start = SequenceItem(book = 5, chapter = 20), end = SequenceItem(book = 5, chapter = 22)),
    Sequence(start = SequenceItem(book = 5, chapter = 23), end = SequenceItem(book = 5, chapter = 26)),
    Sequence(start = SequenceItem(book = 5, chapter = 27), end = SequenceItem(book = 5, chapter = 28)),
    Sequence(start = SequenceItem(book = 5, chapter = 29), end = SequenceItem(book = 5, chapter = 31)),
    Sequence(start = SequenceItem(book = 5, chapter = 32), end = SequenceItem(book = 5, chapter = 32)),
    Sequence(start = SequenceItem(book = 5, chapter = 33), end = SequenceItem(book = 5, chapter = 34)),
    // JOSHUA
    Sequence(start = SequenceItem(book = 6, chapter = 1), end = SequenceItem(book = 6, chapter = 4)),
    Sequence(start = SequenceItem(book = 6, chapter = 5), end = SequenceItem(book = 6, chapter = 7)),
    Sequence(start = SequenceItem(book = 6, chapter = 8), end = SequenceItem(book = 6, chapter = 9)),
    Sequence(start = SequenceItem(book = 6, chapter = 10), end = SequenceItem(book = 6, chapter = 12)),
    Sequence(start = SequenceItem(book = 6, chapter = 13), end = SequenceItem(book = 6, chapter = 15)),
    Sequence(start = SequenceItem(book = 6, chapter = 16), end = SequenceItem(book = 6, chapter = 18)),
    Sequence(start = SequenceItem(book = 6, chapter = 19), end = SequenceItem(book = 6, chapter = 21)),
    Sequence(start = SequenceItem(book = 6, chapter = 22), end = SequenceItem(book = 6, chapter = 24)),
    // JUDGES
    Sequence(start = SequenceItem(book = 7, chapter = 1), end = SequenceItem(book = 7, chapter = 2)),
    Sequence(start = SequenceItem(book = 7, chapter = 3), end = SequenceItem(book = 7, chapter = 5)),
    Sequence(start = SequenceItem(book = 7, chapter = 6), end = SequenceItem(book = 7, chapter = 7)),
    Sequence(start = SequenceItem(book = 7, chapter = 8), end = SequenceItem(book = 7, chapter = 9)),
    Sequence(start = SequenceItem(book = 7, chapter = 10), end = SequenceItem(book = 7, chapter = 11)),
    Sequence(start = SequenceItem(book = 7, chapter = 12), end = SequenceItem(book = 7, chapter = 13)),
    Sequence(start = SequenceItem(book = 7, chapter = 14), end = SequenceItem(book = 7, chapter = 16)),
    Sequence(start = SequenceItem(book = 7, chapter = 17), end = SequenceItem(book = 7, chapter = 19)),
    Sequence(start = SequenceItem(book = 7, chapter = 20), end = SequenceItem(book = 7, chapter = 21)),
    // RUTH
    Sequence(start = SequenceItem(book = 8, chapter = 1), end = SequenceItem(book = 8, chapter = 4)),
    // 1 SAMUEL
    Sequence(start = SequenceItem(book = 9, chapter = 1), end = SequenceItem(book = 9, chapter = 2)),
    Sequence(start = SequenceItem(book = 9, chapter = 3), end = SequenceItem(book = 9, chapter = 6)),
    Sequence(start = SequenceItem(book = 9, chapter = 7), end = SequenceItem(book = 9, chapter = 9)),
    Sequence(start = SequenceItem(book = 9, chapter = 10), end = SequenceItem(book = 9, chapter = 12)),
    Sequence(start = SequenceItem(book = 9, chapter = 13), end = SequenceItem(book = 9, chapter = 14)),
    Sequence(start = SequenceItem(book = 9, chapter = 15), end = SequenceItem(book = 9, chapter = 16)),
    Sequence(start = SequenceItem(book = 9, chapter = 17), end = SequenceItem(book = 9, chapter = 18)),
    Sequence(start = SequenceItem(book = 9, chapter = 19), end = SequenceItem(book = 9, chapter = 21)),
    Sequence(start = SequenceItem(book = 9, chapter = 22), end = SequenceItem(book = 9, chapter = 24)),
    Sequence(start = SequenceItem(book = 9, chapter = 25), end = SequenceItem(book = 9, chapter = 27)),
    Sequence(start = SequenceItem(book = 9, chapter = 28), end = SequenceItem(book = 9, chapter = 31)),
    // 2 SAMUEL
    Sequence(start = SequenceItem(book = 10, chapter = 1), end = SequenceItem(book = 10, chapter = 2)),
    Sequence(start = SequenceItem(book = 10, chapter = 3), end = SequenceItem(book = 10, chapter = 5)),
    Sequence(start = SequenceItem(book = 10, chapter = 6), end = SequenceItem(book = 10, chapter = 8)),
    Sequence(start = SequenceItem(book = 10, chapter = 9), end = SequenceItem(book = 10, chapter = 12)),
    Sequence(start = SequenceItem(book = 10, chapter = 13), end = SequenceItem(book = 10, chapter = 14)),
    Sequence(start = SequenceItem(book = 10, chapter = 15), end = SequenceItem(book = 10, chapter = 16)),
    Sequence(start = SequenceItem(book = 10, chapter = 17), end = SequenceItem(book = 10, chapter = 18)),
    Sequence(start = SequenceItem(book = 10, chapter = 19), end = SequenceItem(book = 10, chapter = 20)),
    Sequence(start = SequenceItem(book = 10, chapter = 21), end = SequenceItem(book = 10, chapter = 22)),
    Sequence(start = SequenceItem(book = 10, chapter = 23), end = SequenceItem(book = 10, chapter = 24)),
    // 1 KINGS
    Sequence(start = SequenceItem(book = 11, chapter = 1), end = SequenceItem(book = 11, chapter = 2)),
    Sequence(start = SequenceItem(book = 11, chapter = 3), end = SequenceItem(book = 11, chapter = 5)),
    Sequence(start = SequenceItem(book = 11, chapter = 6), end = SequenceItem(book = 11, chapter = 7)),
    Sequence(start = SequenceItem(book = 11, chapter = 8), end = SequenceItem(book = 11, chapter = 8)),
    Sequence(start = SequenceItem(book = 11, chapter = 9), end = SequenceItem(book = 11, chapter = 10)),
    Sequence(start = SequenceItem(book = 11, chapter = 11), end = SequenceItem(book = 11, chapter = 12)),
    Sequence(start = SequenceItem(book = 11, chapter = 13), end = SequenceItem(book = 11, chapter = 14)),
    Sequence(start = SequenceItem(book = 11, chapter = 15), end = SequenceItem(book = 11, chapter = 17)),
    Sequence(start = SequenceItem(book = 11, chapter = 18), end = SequenceItem(book = 11, chapter = 19)),
    Sequence(start = SequenceItem(book = 11, chapter = 20), end = SequenceItem(book = 11, chapter = 21)),
    Sequence(start = SequenceItem(book = 11, chapter = 22), end = SequenceItem(book = 11, chapter = 22)),
    // 2 KINGS
    Sequence(start = SequenceItem(book = 12, chapter = 1), end = SequenceItem(book = 11, chapter = 3)),
    Sequence(start = SequenceItem(book = 12, chapter = 4), end = SequenceItem(book = 11, chapter = 5)),
    Sequence(start = SequenceItem(book = 12, chapter = 6), end = SequenceItem(book = 11, chapter = 8)),
    Sequence(start = SequenceItem(book = 12, chapter = 9), end = SequenceItem(book = 11, chapter = 10)),
    Sequence(start = SequenceItem(book = 12, chapter = 11), end = SequenceItem(book = 11, chapter = 13)),
    Sequence(start = SequenceItem(book = 12, chapter = 14), end = SequenceItem(book = 11, chapter = 15)),
    Sequence(start = SequenceItem(book = 12, chapter = 16), end = SequenceItem(book = 11, chapter = 17)),
    Sequence(start = SequenceItem(book = 12, chapter = 18), end = SequenceItem(book = 11, chapter = 19)),
    Sequence(start = SequenceItem(book = 12, chapter = 20), end = SequenceItem(book = 11, chapter = 22)),
    Sequence(start = SequenceItem(book = 12, chapter = 23), end = SequenceItem(book = 11, chapter = 25)),
    // 1 Chronicles
    Sequence(start = SequenceItem(book = 13, chapter = 1), end = SequenceItem(book = 13, chapter = 2)),
    Sequence(start = SequenceItem(book = 13, chapter = 3), end = SequenceItem(book = 13, chapter = 5)),
    Sequence(start = SequenceItem(book = 13, chapter = 6), end = SequenceItem(book = 13, chapter = 7)),
    Sequence(start = SequenceItem(book = 13, chapter = 8), end = SequenceItem(book = 13, chapter = 10)),
    Sequence(start = SequenceItem(book = 13, chapter = 11), end = SequenceItem(book = 13, chapter = 12)),
    Sequence(start = SequenceItem(book = 13, chapter = 13), end = SequenceItem(book = 13, chapter = 15)),
    Sequence(start = SequenceItem(book = 13, chapter = 16), end = SequenceItem(book = 13, chapter = 17)),
    Sequence(start = SequenceItem(book = 13, chapter = 18), end = SequenceItem(book = 13, chapter = 20)),
    Sequence(start = SequenceItem(book = 13, chapter = 18), end = SequenceItem(book = 13, chapter = 20)),
    Sequence(start = SequenceItem(book = 13, chapter = 21), end = SequenceItem(book = 13, chapter = 23)),
    Sequence(start = SequenceItem(book = 13, chapter = 24), end = SequenceItem(book = 13, chapter = 26)),
    Sequence(start = SequenceItem(book = 13, chapter = 27), end = SequenceItem(book = 13, chapter = 29)),
    // 2 Chronicles
    Sequence(start = SequenceItem(book = 14, chapter = 1), end = SequenceItem(book = 14, chapter = 3)),
    Sequence(start = SequenceItem(book = 14, chapter = 4), end = SequenceItem(book = 14, chapter = 6)),
    Sequence(start = SequenceItem(book = 14, chapter = 7), end = SequenceItem(book = 14, chapter = 9)),
    Sequence(start = SequenceItem(book = 14, chapter = 10), end = SequenceItem(book = 14, chapter = 14)),
    Sequence(start = SequenceItem(book = 14, chapter = 15), end = SequenceItem(book = 14, chapter = 18)),
    Sequence(start = SequenceItem(book = 14, chapter = 19), end = SequenceItem(book = 14, chapter = 22)),
    Sequence(start = SequenceItem(book = 14, chapter = 23), end = SequenceItem(book = 14, chapter = 25)),
    Sequence(start = SequenceItem(book = 14, chapter = 26), end = SequenceItem(book = 14, chapter = 28)),
    Sequence(start = SequenceItem(book = 14, chapter = 29), end = SequenceItem(book = 14, chapter = 30)),
    Sequence(start = SequenceItem(book = 14, chapter = 31), end = SequenceItem(book = 14, chapter = 33)),
    Sequence(start = SequenceItem(book = 14, chapter = 34), end = SequenceItem(book = 14, chapter = 36)),
    // Ezra
    Sequence(start = SequenceItem(book = 15, chapter = 1), end = SequenceItem(book = 15, chapter = 3)),
    Sequence(start = SequenceItem(book = 15, chapter = 4), end = SequenceItem(book = 15, chapter = 7)),
    Sequence(start = SequenceItem(book = 15, chapter = 8), end = SequenceItem(book = 15, chapter = 10)),
    // Nehemiah
    Sequence(start = SequenceItem(book = 16, chapter = 1), end = SequenceItem(book = 16, chapter = 3)),
    Sequence(start = SequenceItem(book = 16, chapter = 4), end = SequenceItem(book = 16, chapter = 6)),
    Sequence(start = SequenceItem(book = 16, chapter = 7), end = SequenceItem(book = 16, chapter = 8)),
    Sequence(start = SequenceItem(book = 16, chapter = 9), end = SequenceItem(book = 16, chapter = 10)),
    Sequence(start = SequenceItem(book = 16, chapter = 11), end = SequenceItem(book = 16, chapter = 13)),
    // Esther
    Sequence(start = SequenceItem(book = 17, chapter = 1), end = SequenceItem(book = 17, chapter = 4)),
    Sequence(start = SequenceItem(book = 17, chapter = 5), end = SequenceItem(book = 17, chapter = 10)),
    // Job
    Sequence(start = SequenceItem(book = 18, chapter = 1), end = SequenceItem(book = 18, chapter = 5)),
    Sequence(start = SequenceItem(book = 18, chapter = 6), end = SequenceItem(book = 18, chapter = 9)),
    Sequence(start = SequenceItem(book = 18, chapter = 10), end = SequenceItem(book = 18, chapter = 14)),
    Sequence(start = SequenceItem(book = 18, chapter = 15), end = SequenceItem(book = 18, chapter = 18)),
    Sequence(start = SequenceItem(book = 18, chapter = 19), end = SequenceItem(book = 18, chapter = 20)),
    Sequence(start = SequenceItem(book = 18, chapter = 21), end = SequenceItem(book = 18, chapter = 24)),
    Sequence(start = SequenceItem(book = 18, chapter = 25), end = SequenceItem(book = 18, chapter = 29)),
    Sequence(start = SequenceItem(book = 18, chapter = 30), end = SequenceItem(book = 18, chapter = 31)),
    Sequence(start = SequenceItem(book = 18, chapter = 32), end = SequenceItem(book = 18, chapter = 34)),
    Sequence(start = SequenceItem(book = 18, chapter = 35), end = SequenceItem(book = 18, chapter = 38)),
    Sequence(start = SequenceItem(book = 18, chapter = 39), end = SequenceItem(book = 18, chapter = 42)),
    // Psalms
    Sequence(start = SequenceItem(book = 19, chapter = 1), end = SequenceItem(book = 19, chapter = 8)),
    Sequence(start = SequenceItem(book = 19, chapter = 9), end = SequenceItem(book = 19, chapter = 16)),
    Sequence(start = SequenceItem(book = 19, chapter = 17), end = SequenceItem(book = 19, chapter = 19)),
    Sequence(start = SequenceItem(book = 19, chapter = 20), end = SequenceItem(book = 19, chapter = 25)),
    Sequence(start = SequenceItem(book = 19, chapter = 26), end = SequenceItem(book = 19, chapter = 31)),
    Sequence(start = SequenceItem(book = 19, chapter = 32), end = SequenceItem(book = 19, chapter = 35)),
    Sequence(start = SequenceItem(book = 19, chapter = 36), end = SequenceItem(book = 19, chapter = 38)),
    Sequence(start = SequenceItem(book = 19, chapter = 39), end = SequenceItem(book = 19, chapter = 42)),
    Sequence(start = SequenceItem(book = 19, chapter = 43), end = SequenceItem(book = 19, chapter = 47)),
    Sequence(start = SequenceItem(book = 19, chapter = 48), end = SequenceItem(book = 19, chapter = 52)),
    Sequence(start = SequenceItem(book = 19, chapter = 53), end = SequenceItem(book = 19, chapter = 58)),
    Sequence(start = SequenceItem(book = 19, chapter = 59), end = SequenceItem(book = 19, chapter = 64)),
    Sequence(start = SequenceItem(book = 19, chapter = 65), end = SequenceItem(book = 19, chapter = 68)),
    Sequence(start = SequenceItem(book = 19, chapter = 69), end = SequenceItem(book = 19, chapter = 72)),
    Sequence(start = SequenceItem(book = 19, chapter = 73), end = SequenceItem(book = 19, chapter = 77)),
    Sequence(start = SequenceItem(book = 19, chapter = 78), end = SequenceItem(book = 19, chapter = 79)),
    Sequence(start = SequenceItem(book = 19, chapter = 80), end = SequenceItem(book = 19, chapter = 86)),
    Sequence(start = SequenceItem(book = 19, chapter = 87), end = SequenceItem(book = 19, chapter = 90)),
    Sequence(start = SequenceItem(book = 19, chapter = 91), end = SequenceItem(book = 19, chapter = 96)),
    Sequence(start = SequenceItem(book = 19, chapter = 97), end = SequenceItem(book = 19, chapter = 103)),
    Sequence(start = SequenceItem(book = 19, chapter = 104), end = SequenceItem(book = 19, chapter = 105)),
    Sequence(start = SequenceItem(book = 19, chapter = 106), end = SequenceItem(book = 19, chapter = 108)),
    Sequence(start = SequenceItem(book = 19, chapter = 109), end = SequenceItem(book = 19, chapter = 115)),
    Sequence(start = SequenceItem(book = 19, chapter = 116), end = SequenceItem(book = 19, chapter = 119)),
    Sequence(start = SequenceItem(book = 19, chapter = 119), end = SequenceItem(book = 19, chapter = 119)),
    Sequence(start = SequenceItem(book = 19, chapter = 120), end = SequenceItem(book = 19, chapter = 129)),
    Sequence(start = SequenceItem(book = 19, chapter = 130), end = SequenceItem(book = 19, chapter = 138)),
    Sequence(start = SequenceItem(book = 19, chapter = 139), end = SequenceItem(book = 19, chapter = 144)),
    Sequence(start = SequenceItem(book = 19, chapter = 145), end = SequenceItem(book = 19, chapter = 150)),
    // Proverbs
    Sequence(start = SequenceItem(book = 20, chapter = 1), end = SequenceItem(book = 20, chapter = 4)),
    Sequence(start = SequenceItem(book = 20, chapter = 5), end = SequenceItem(book = 20, chapter = 8)),
    Sequence(start = SequenceItem(book = 20, chapter = 9), end = SequenceItem(book = 20, chapter = 12)),
    Sequence(start = SequenceItem(book = 20, chapter = 13), end = SequenceItem(book = 20, chapter = 16)),
    Sequence(start = SequenceItem(book = 20, chapter = 17), end = SequenceItem(book = 20, chapter = 19)),
    Sequence(start = SequenceItem(book = 20, chapter = 20), end = SequenceItem(book = 20, chapter = 22)),
    Sequence(start = SequenceItem(book = 20, chapter = 23), end = SequenceItem(book = 20, chapter = 27)),
    Sequence(start = SequenceItem(book = 20, chapter = 28), end = SequenceItem(book = 20, chapter = 31)),
    // Ecclesiastes
    Sequence(start = SequenceItem(book = 21, chapter = 1), end = SequenceItem(book = 21, chapter = 4)),
    Sequence(start = SequenceItem(book = 21, chapter = 5), end = SequenceItem(book = 21, chapter = 8)),
    Sequence(start = SequenceItem(book = 21, chapter = 9), end = SequenceItem(book = 21, chapter = 12)),
    // Song Of Solomon
    Sequence(start = SequenceItem(book = 22, chapter = 1), end = SequenceItem(book = 22, chapter = 8)),

    )
